www/apps/users/urls.py
from django.conf.urls import url

from users.views import LoginView, RegisterView, MemberView, SaftyView, PasswordView, ForgetpasswordView, InfoView, \
    BoundphoneView, SendMsg

urlpatterns = [
    url(r'^login/$',LoginView.as_view(),name='登录' ),
    url(r'^register/$',RegisterView.as_view(),name='注册' ),
    url(r'^member/$',MemberView.as_view(),name='个人中心' ),
    url(r'^safty/$',SaftyView.as_view(),name='安全设置' ),
    url(r'^password/$',PasswordView.as_view(),name='修改密码' ),
    url(r'^forgetpassword/$',ForgetpasswordView.as_view(),name='忘记密码' ),
    url(r'^info/$',InfoView.as_view(),name='个人资料' ),
    url(r'^boundphone/$',BoundphoneView.as_view(),name='绑定手机号' ),
    url(r'^sendmsg/$',SendMsg.as_view(),name='发送短信验证码' ),
]

www/www/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^cart/', include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls',namespace='order')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^$',IndexView.as_view())
]

www/apps/users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator


# Create your models here.
from db.base_model import BaseModel


class Users(BaseModel):
    num = models.CharField(max_length=11,
                                validators=[
                                    MinLengthValidator(11, '手机号码必须为11位'),
                                    RegexValidator(r'^1[3-9]\d{9}$', "手机号码格式错误!")
                                ])
    gender_choices = (
        (1,'男'),
        (2,'女'))
    password = models.CharField(max_length=32)
    is_delete = models.BooleanField(default=False)
    create_time = models.DateField(auto_now_add=True) #添加时间
    update_time = models.DateField(auto_now=True) #修改时间
    nickname=models.CharField(max_length=200,null=True,blank=True)  #昵称
    birthday=models.DateField(null=True,blank=True)
    gender=models.SmallIntegerField(choices=gender_choices,default=1)
    school=models.CharField(null=True,max_length=200,blank=True)
    location=models.CharField(null=True,max_length=200,blank=True)
    hometown=models.CharField(null=True,max_length=200,blank=True)
    # 设置头像字段
    head = models.ImageField(upload_to="head/%Y%m", default="head/memtx.png", verbose_name="用户头像")
    def __str__(self):
        return self.num

    class Meta:
        db_table = "users"
        verbose_name='用户信息'
        verbose_name_plural=verbose_name

www/apps/users/views.py
import re
import random
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django_redis import get_redis_connection
# Create your views here.
from django.utils.decorators import method_decorator
from django.views import View

# 登录
from db.base_view import VerifyLoginView
from users import set_password
from users.form import RegisterModelForm, LoginModelForm, PasswordModelForm, ForgetpasswordModelForm
from users.helper import check_login, login
from users.models import Users


# 登录
class LoginView(View):
    # 展示登录页面
    def get(self, request):
        return render(request, 'users/login.html')

    def post(self, request):
        # 接受数据
        data = request.POST
        form = LoginModelForm(data)
        # 判断是否合法
        if form.is_valid():
            # 验证成功
            # 保存登录标识到session中, 单独创建一个方法保存, 更新个人资料
            user = form.cleaned_data['user']
            login(request, user)
            return redirect('users:个人中心')
        else:
            return render(request, 'users/login.html', context={'form': form})


# 注册
class RegisterView(View):
    # get请求 展示登录表单
    def get(self, request):
        return render(request, 'users/reg.html')

    def post(self, request):
        # post请求 接受参数
        data = request.POST
        # 表单验证
        form = RegisterModelForm(data)
        # 表单验证成功
        if form.is_valid():
            # 操作数据库
            cleande_data = form.cleaned_data
            user = Users()
            user.num = cleande_data.get('num')
            user.password = set_password(cleande_data.get('password'))
            user.save()
            return redirect('users:登录')
        else:
            return render(request, 'users/reg.html', context={'form': form})


# 发送短信
class SendMsg(View):
    def get(self, request):
        pass

    def post(self, request):
        # 接受参数
        num = request.POST.get('num', '')
        rs = re.search('^1[3-9]\d{9}$', num)
        # 判断电话号码的合法性
        if rs is None:
            return JsonResponse({'error': 1, 'errormsg': '电话号码错误'})


        # 处理数据
        # 模拟,最后接入运营商
        # """
        #     1. 生成随机验证码
        #     2. 保存验证码 保存到redis中, 存取速度快,并且可以方便的设置有效时间
        #     3. 接入运营商
        # """
        # >>>1. 生成随机验证码字符串
        random_code = "".join([str(random.randint(0, 9)) for _ in range(6)])
        print("=============随机验证码为==={}==============".format(random_code))

        # >>>2. 保存验证码到redis中
        # 获取连接
        r = get_redis_connection()
        # 保存手机号码对应的验证码
        r.set(num, random_code)
        r.expire(num, 60)  # 设置60秒后过期

        # 首先获取当前手机号码的发送次数
        key_times = "{}_times".format(num)
        now_times = r.get(key_times)  # 从redis获取的二进制,需要转换
        # print(int(now_times))
        if now_times is None or int(now_times) < 5:
            # 保存手机发送验证码的次数, 不能超过5次
            r.incr(key_times)
            # 设置一个过期时间
            r.expire(key_times, 3600)  # 一个小时后再发送
        else:
            # 返回,告知用户发送次数过多
            return JsonResponse({"error": 1, "errmsg": "发送次数过多"})

        return JsonResponse({'error': 0})


# 个人中心
class MemberView(VerifyLoginView):
    def get(self, request):
        return render(request, 'users/member.html')

    def post(self, request):
        pass


# 安全中心
class SaftyView(VerifyLoginView):
    def get(self, request):
        return render(request, 'users/saftystep.html')

    def post(self, request):
        pass


# 绑定手机号
class BoundphoneView(VerifyLoginView):
    def get(self, request):
        return render(request, 'users/boundphone.html')

    def post(self, request):
        pass


# 修改密码
class PasswordView(VerifyLoginView):
    def get(self, request):
        return render(request, 'users/password.html')

    def post(self, request):
        # return HttpResponse('ok')
        # 接收数据
        data = request.POST
        form = PasswordModelForm(data)
        # 验证表单成功
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # 操作数据库
            password = cleaned_data.get('password')
            newpassword = cleaned_data.get('newpassword')
            # 更新到数据库
            Users.objects.filter(password=password).update(password=set_password(newpassword))
            return redirect('users:登录')
        else:
            return render(request, 'users/password.html', context={'form': form})


# 忘记密码
class ForgetpasswordView(VerifyLoginView):
    def get(self, request):
        return render(request, 'users/forgetpassword.html')

    def post(self, request):
        # 接收数据
        data = request.POST
        form = ForgetpasswordModelForm(data)
        # 验证表单成功
        if form.is_valid():
            cleaned_data = form.cleaned_data
            # 操作数据库
            num = cleaned_data.get('num')
            password = cleaned_data.get('password')
            newpassword = cleaned_data.get('newpassword')
            # 更新到数据库
            Users.objects.filter(num=num).update(password=set_password(newpassword))
            return redirect('users:登录')
        else:
            return render(request, 'users/forgetpassword.html', context={'form': form})


# 个人资料
class InfoView(VerifyLoginView):
    def get(self, request):
        id = request.session.get('ID')
        num = request.session.get('num')
        user = Users.objects.get(num=num)
        return render(request, 'users/infor.html', context={'user': user})

    def post(self, request):
        # 接收参数
        data = request.POST
        head = request.FILES.get('head')
        id = request.session.get('ID')
        num = request.session.get('num')
        # 验证数据合法性
        nickname = data.get('nickname')
        school = data.get('school')
        hometown = data.get('hometown')
        birthday = data.get('birthday')
        location = data.get('location')
        gender = int(data.get('gender'))
        user = Users.objects.get(pk=id)
        # 把接收到的参数更新到数据库
        Users.objects.filter(id=id).update(nickname=nickname, school=school, hometown=hometown, birthday=birthday,location=location, gender=gender)
        if head is not None:
            user.head = head
        user.save()
        # 同时修改session
        login(request, user)
        return redirect('users:个人中心')

www/templates/users/boundphone.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
<title>绑定手机号</title>
{% endblock %}
{% block content %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">绑定新手机号</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="pay-iphone">请填写新手机号并进行验证</div>
	    <div class="pay-box">
	    	<input type="text" placeholder="请输入新手机号" />
	    	<input type="button" value="获取验证码" class="pay-box-btn" />
	    </div>
	    <input type="text" placeholder="请输入验证码" class="login-password" />
	    <input type="button" class="login-btn" value="确认">
	    <div class="bound-text">
		    <h2>手机绑定规则</h2>
		    <p>1.一个手机号码只可以绑定一个账户；</p>
	        <p>2.如果无法绑定手机，请联系客服协助解决。</p>
        </div>
{% endblock %}

www/templates/users/forgetpassword.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
<title>忘记密码</title>
{% endblock %}
{% block content %}
   <form action="" method="post" class="form-horizontal">
   {% csrf_token %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">忘记密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>

	    <input type="text" name="num"  placeholder="请输入手机号" class="login-password">
       <p class="am-text-danger">{{ form.errors.num.0 }}</p>
	    <div class="yzm">
	    	<input type="text" class="reg-yzm" placeholder="输入验证码" />
	    	<input type="button" class="yzm-hq" value="获取验证码" />
	    </div>
	    <input type="password" name="newpassword"  placeholder="请输入密码" class="login-password">
       <p class="am-text-danger">{{ form.errors.newpassword.0 }}</p>
	    <input type="password" name="renewpassword"  placeholder="确认密码" class="login-name">
       <p class="am-text-danger">{{ form.errors.renewpassword.0 }}</p>
	    <input type="submit" class="login-btn" value="立即提交">
    </form>
{% endblock %}

www/templates/users/infor.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
<title>个人资料</title>
{% endblock %}
{% block content %}
     <form action="" method="post" class="form-horizontal" enctype="multipart/form-data">
   {% csrf_token %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="{% url 'users:个人资料' %}" class="">个人资料</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="safty1">
	    	<li>
	    			<i style="margin-top: 25px;">头像</i>
	    			<div class="infor-pic">
	    				<img src="{{ MEDIA_URL }}{{ user.head }}" />
	    			</div>
	    	</li>
            <li>
            <input type="file" name="head">
        </li>
	    	<li>
	    			<i>昵称</i>
	    			<input name="nickname" class="infor-tele" placeholder="默契"/>
	    	</li>
	    	<li>

	    			<i>性别</i>
	    			<i class="infor-tele">
	    				<label class="am-radio-inline">
				          <input name="gender" type="radio"  checked="checked" value="1" data-am-ucheck>男
				        </label>
				        <label class="am-radio-inline">
				          <input name="gender" type="radio"  value="2" data-am-ucheck>女
				        </label>
	    			</i>

	    	</li><li>

	    			<i>生日</i>
                    <input name="birthday" type="date" class="infor-tele" value="{{ user.birthday|date:'Y-m-d'}}"/>
	    	</li>
            <p class="am-text-danger">{{ form.errors.birthday.0 }}</p>
	    </ul>
	    <div style="height: 10px; background: #efefef;"></div>
	     <ul class="safty1">
	    	<li>
	    			<i>学校</i>
	    			<input name="school" class="infor-tele" value="{{ user.school}}"/>
	    	</li>
	    	<li>
	    			<i>位置</i>
	    			<input name="location" class="infor-tele" value=" {{ user.location}}"/>
	    	</li>
	    	<li>
	    			<i>故乡</i>
                    <input name="hometown" class="infor-tele" value="{{ user.hometown}}"/>
	    	</li>
	    	<li>
	    			<i>手机</i>
                <input disabled name="num" class="infor-tele"  value="{{ user.num}}">
            </li>
	    </ul>
     	    <input type="submit" class="login-btn" value="保存">
    </form>
{% endblock %}

www/templates/users/login.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
<title>登录</title>
{% endblock %}
{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
    <input type="text" name="num" id="num" placeholder="请输入用户名/手机号" class="login-name" value="{{ request.POST.num }}">
        <p class="am-text-danger">{{ form.errors.num.0 }}</p>
        <input type="password" name="password" id="password" placeholder="请输入密码" class="login-name">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>
    <input type="submit" class="login-btn" value="我要登录">
    <div class="agree">
        <a href="{% url 'users:注册' %}">免费注册</a>
        <a href="{% url 'users:忘记密码' %}" class="forget">忘记密码？</a>
    </div>
    <div class="line"></div>
    <div class="line-text">第三方账号登录</div>
    <ul class="second-login">
        <li><a href=""><img src="{% static 'images/wxlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
        <li><a href=""><img src="{% static 'images/qqlogin.png' %}"/></a></li>
    </ul>
    </form>
{% endblock %}

www/templates/users/member.html
{% extends 'common/parents.html' %}
{% load static %}
{% block content %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<h1 class="am-header-title">
  	            <a href="" class="">个人中心</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <div class="member">
	    	<div class="mem-tit">{{ request.session.num }}
	    		<a href="step.html" class="step"><img src="{% static 'images/step.png' %}" width="26"/></a>
	    	</div>
	    	<div class="mem-pic">
		    	<div class="mem-pic-bg" style="background-image: url({{ MEDIA_URL }}{{ request.session.head }});"></div>
	    	</div>
	    	<ul class="member-menu">
			<li>
				<a href="records.html">
					<p class="yellow">0</p>
					<p class="black">帐户余额 </p>
				</a>
			</li>
            <li>
				<a href="integral.html">
					<p class="yellow">0</p>
					<p class="black">积分 </p>
				</a>
			</li>
			<li>
				<a href="yhq.html">
					<p class="yellow">0</p>
					<p class="black">优惠劵 </p>
				</a>
			</li>
			<li>
				<a href="collect.html">
					<p class="yellow">0</p>
					<p class="black">我的收藏 </p>
				</a>
			</li>
		</ul>
	    </div>
	    <div class="user-list">
		  	<div class="u-list-main">
		  		<img src="{% static 'images/order-pic.png' %}" width="27" />
		  		<span>我的购物订单</span>
		  		<a href="allorder.html">查看全部订单></a>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon.png' %}"> <p>待付款</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon1.png' %}"> <p>待收货</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon2.png' %}"> <p>待评价</p></a></li>
		    	<li><a href="allorder.html"> <img src="{% static 'images/1-icon3.png' %}"> <p>退换货</p></a></li>
		    </ul>
		    <div class="u-list-main">
		  		<img src="{% static 'images/order-my.png' %}" width="27" />
		  		<span>帐户与安全</span>
		  	</div>
		    <ul class="user-nav">
		    	<li><a href="{% url 'users:个人资料' %}"> <img src="{% static 'images/1-icon4.png' %}"> <p>个人资料</p></a></li>
		    	<li><a href="gladdress.html"> <img src="{% static 'images/1-icon5.png' %}"> <p>收货地址</p></a></li>
		    	<li><a href="{% url 'users:安全设置' %}"> <img src="{% static 'images/1-icon6.png' %}"> <p>安全设置</p></a></li>
		    	<li><a href="money.html"> <img src="{% static 'images/1-icon7.png' %}"> <p>我的钱包</p></a></li>
		    </ul>
	    </div>
	    <!--导航-->
 <ul class="sq-nav" style=" background: #fff; margin-top: 1rem; border-top: 1px solid #ddd;  border-bottom: 1px solid #ddd;">
      <li>
        <div class="am-gallery-item">
            <a href="job.html" class="">
              <img src="{% static 'images/m_03.png' %}" />
              <p>我要兼职</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="recommend.html" class="">
              <img src="{% static 'images/m_04.png' %}" />
              <p>推荐有奖</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="myrecommend.html" class="">
              <img src="{% static 'images/m_05.png' %}" />
              <p>我的推荐</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_06.png' %}" />
              <p>我的佣金</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="yhq.html" class="">
              <img src="{% static 'images/m_02.png' %}" />
              <p>我的红包</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="message.html" class="">
              <img src="{% static 'images/m_07.png' %}" />
              <p>我的动态</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="javascript:;" class="index-qd">
              <img src="{% static 'images/m_08.png' %}" />
              <p>客服中心</p>
            </a>
        </div>
      </li>
      <li>
        <div class="am-gallery-item">
            <a href="" class="">
              <img src="{% static 'images/m_09.png' %}" />
              <p>安全退出</p>
            </a>
        </div>
      </li>
      </ul>
      </div>
    <!--客服中心-->
<div class="qd-box">
	<div class="popup-title">
			<span>客服中心</span>
			<div class="popup-close"><i class="iconfont">&#xe602</i></div>
	</div>
	<div class="dq-text">
		<a href="http://wpa.qq.com/msgrd?v=3&uin=123456789&site=qq&menu=yes">
			<img src="images/contactqq.png" width="50" />
			<p class="contactqq">联系QQ</p>
		</a>
		<a href="tel:0791-12345678">
			<img src="images/contacttele.png"  width="50" />
			<p class="contacttele">呼叫电话</p>
		</a>
	</div>
</div>
<!--客服中心-->
      <!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="{% url 'goods:首页' %}" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>




 <script type='text/javascript'>
	(function(){
		 new PopUp_api({el:'.index-qd',html:'.qd-box'});
	})()
</script>

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/amazeui.min.js' %}"></script>
{% endblock %}

www/templates/users/password.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
<title>修改密码</title>
{% endblock %}
{% block content %}
        <form action="" method="post" class="form-horizontal">
         {% csrf_token %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">修改密码</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <input type="password" name="password" placeholder="旧密码" class="login-password">
             <p class="am-text-danger">{{ form.errors.password.0 }}</p>
	    <input type="password" name="newpassword" placeholder="新密码" class="login-name">
             <p class="am-text-danger">{{ form.errors.newpassword.0 }}</p>
	    <input type="password" name="renewpassword" placeholder="确认新密码" class="login-password">
             <p class="am-text-danger">{{ form.errors.renewpassword.0 }}</p>
	    <input type="submit" class="login-btn" value="确认">
        </form>>
{% endblock %}

www/templates/users/reg.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
    <title>注册</title>
{% endblock %}
{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <h1 class="am-header-title">
            <a href="" class="">注册</a>
        </h1>
    </header>
    <div style="height: 49px;"></div>
    <div style="height: 3rem;"></div>
{% endblock %}
{% block content %}
    <form action="" method="post" class="form-horizontal">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" name="num" id='num' placeholder="请输入手机号" value="{{ request.POST.num }}"
                   class="login-name">
            <p class="am-text-danger">{{ form.errors.num.0 }}</p>
        </div>
        <input type="password" name="password" placeholder="请输入密码" class="login-password">
        <p class="am-text-danger">{{ form.errors.password.0 }}</p>

        <input type="password" name="repassword" placeholder="确认密码" class="login-name">
        <p class="am-text-danger">{{ form.errors.repassword.0 }}</p>
        <div class="yzm" style="margin-top: 1.5rem;">
            <input type="text" class="reg-yzm" name="captcha" placeholder="输入验证码"/>
            <input type="button" class="yzm-hq" value="获取验证码"/>
            </div>
        <p class="am-text-danger">{{ form.errors.captcha.0 }}</p>
            <input type="submit" class="login-btn" value="立即注册">
            <div class="agree">
                <input type="checkbox" name="agree" value="同意" checked="">&nbsp;同意
                <a href="" class="xy">《用户协议》</a>
                <p class="am-text-danger">{{ form.errors.agree.0 }}</p>

                <div class="r-login">已有账号，请<a href="{% url 'users:登录' %}" class="l-login">登录</a></div>
            </div>
        </div>
    </form>
{% endblock %}

{% block footer_js %}
    <script type="text/javascript">
        {#    js 代码在网页加载完毕后才执行#}
        $(function () {
            //网页加载完毕后执行
            //1绑定点击时间
            $('.yzm-hq').on('click', function () {
                console.debug(11)
                //2获取手机号码
                var num = $('#num').val();
                var reg = /^1[3-9]\d{9}$/;
                {#console.debug(reg.test(num));#}
                if (!reg.test(num)) {
                    alert('手机号码错误');
                    return;
                }
                var self = this
                //3发送ajax请求
                $.ajax({
                    type: 'post',
                    url: '{% url "users:发送短信验证码" %}',
                    data: {'num': num, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
                    dataType: 'json',
                    success: function (data) {
                        {#console.debug(data)#}
                        //判断是否发送成功
                        if (data.error == 0) {
                            //1改变颜色
                            $(self).css('background-color', 'gray');
                            //2按钮不能在点击
                            $(self).prop('disabled', true);
                            //3倒计时 周期性执行函数
                            var time = 60;
                            var msg = time + '秒后重新发送';
                            $(self).val(msg);
                            var timer = window.setInterval(function () {
                                time -= 1;
                                msg = time + '秒后重新发送';
                                $(self).val(msg);
                                if (time == 0) {
                                    //回到没点击之前
                                    //1改变颜色
                                    $(self).css('background-color', '#76bb2a');
                                    //2按钮不能在点击
                                    $(self).prop('disabled', false);
                                    //3返回原来的文字
                                    $(self).val('获取验证码');
                                    //4清除定时
                                    window.clearInterval(timer);
                                    return;
                                }
                            }, 1000);
                        } else
                            alert('短信验证失败')
                    }
                })
            })
        })
    </script>
{% endblock %}

www/templates/users/saftystep.html
{% extends 'common/parents.html' %}
{% load static %}
{% block content %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">安全设置</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="safty">
	    	<li>
	    		<a href="{% url 'users:修改密码' %}">
	    			<img src="{% static 'images/update.png' %}" width="40" />
	    			<i>修改登录密码</i>
	    			<span class="am-icon-angle-right"></span>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="payment.html">
	    			<img src="{% static 'images/moneysafty.png' %}" width="40" />
	    			<i>设置支付密码</i>
	    			<span class="am-icon-angle-right"></span>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="{% url 'users:绑定手机号' %}">
	    			<img src="{% static 'images/moneytele.png' %}" width="40" />
	    			<i>绑定手机号</i>
	    			<span class="am-icon-angle-right"></span>
	    			<i style="float: right; padding-right: 10px;">136****3128</i>
	    		</a>
	    		<p style="overflow: hidden;">若你的手机已修改或信用，请立即更换</p>
	    	</li>
	    </ul>
{% endblock %}