www/apps/goods/urls.py
from django.conf.urls import url

from goods.views import  CategoryView, DetailView, TidingsView, CityView

urlpatterns = [
    url(r'^category/$',CategoryView.as_view(),name='超市'),
    url(r'^detail/(?P<id>\d+)/$', DetailView.as_view(), name="详情"),
    url(r'^tidings/$',TidingsView.as_view(),name='消息中心'),
    url(r'^city/$',CityView.as_view(),name='城市'),
]

www/www/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from goods.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 上传部件自动调用的上传地址
    url(r'^ckeditor/', include("ckeditor_uploader.urls")),
    url(r'^users/', include('users.urls',namespace='users')),
    url(r'^cart/', include('cart.urls',namespace='cart')),
    url(r'^order/', include('order.urls',namespace='order')),
    url(r'^goods/', include('goods.urls',namespace='goods')),
    url(r'^$',IndexView.as_view())
]

www/apps/goods/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models

# Create your models here.
from db.base_model import BaseModel


# 1.商品分类表
class GoodsClassModel(BaseModel):
    classname = models.CharField(max_length=6, verbose_name='分类名')
    classintro = models.TextField(max_length=40, verbose_name='分类简介')

    class Meta:
        db_table = 'GoodsClassModel'
        verbose_name = '商品分类信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.classname


# 2.商品SPU表
class GoodsSPUModel(BaseModel):
    SPUname = models.CharField(max_length=50, verbose_name='spu名称')
    SPUdetails = RichTextUploadingField(verbose_name='spu详情')

    class Meta:
        db_table = 'GoodsSPUModel'
        verbose_name = '商品SPU表'
        verbose_name_plural = verbose_name  # 复数名

    def __str__(self):
        return self.SPUname


# 3.商品单位表
class GoodsUnitModel(BaseModel):
    unitname = models.CharField(max_length=10, verbose_name='单位名')

    class Meta:
        db_table = 'GoodsUnitModel'
        verbose_name = '商品单位表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.unitname


# 4.商品sku表
class GoodsskuClassModel(BaseModel):
    goodsname = models.CharField(max_length=10, verbose_name='商品名')
    goodsintro = models.CharField(max_length=30, verbose_name='商品简介')
    goodsprice = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='价格')
    stock = models.SmallIntegerField(verbose_name='库存')
    goodslogo = models.ImageField(upload_to='goodslogo/%y%m/%d', verbose_name='商品logo')
    choic = (
        (False, '未上架'),
        (True, '已上架'),
    )
    shelves = models.BooleanField(choices=choic, verbose_name='是否上架')
    # 商品分类ID  外键  GoodsClassModel
    goodsclass_id = models.ForeignKey(to='GoodsClassModel', verbose_name='商品分类ID')
    # 商品spu_id   外键  GoodsSPUModel
    goodsspu_id = models.ForeignKey(to='GoodsSPUModel', verbose_name='商品spu_id')
    # 单位 外键   UnitModel
    unit = models.ForeignKey(to='GoodsUnitModel', verbose_name='单位')

    class Meta:
        db_table = 'GoodsskuClassModel'
        verbose_name = '商品SKU表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.goodsname


# 5.商品相册表
class GoodsAlbumModel(BaseModel):
    photourl = models.ImageField(upload_to='goods/%y%m/%d', verbose_name='图片地址')
    goodsSKUID = models.ForeignKey(to='GoodsskuClassModel', verbose_name='商品SKUID')

    class Meta:
        db_table = 'GoodsAlbumModel'
        verbose_name = '商品相册表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '商品相册:{}'.format(self.photourl.name)


# 6.首页轮播商品表
class BannerModel(BaseModel):
    goodsName = models.CharField(max_length=30, verbose_name='商品名称')
    # 商品SKUID  外键
    goodsSKU = models.ForeignKey(to=GoodsskuClassModel, verbose_name='商品SKUID')
    # 图片地址
    photourl = models.ImageField(upload_to='banner/%y%m/%d', verbose_name='商品相册')
    # 排序（order）
    bannerOrder = models.SmallIntegerField()

    class Meta:
        db_table = 'BannerModel'
        verbose_name = '首页轮播商品表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.goodsName


# 7 首页活动表
class IndexActModel(models.Model):
    name = models.CharField(max_length=30, verbose_name='名称')
    photourl = models.ImageField(upload_to='activity/%y%m/%d', verbose_name='活动图片')
    # url地址
    url = models.CharField(max_length=100, verbose_name='url地址')

    class Meta:
        db_table = 'IndexActModel'
        verbose_name = '首页活动表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 8首页活动专区
class HomeActarea(BaseModel):
    name = models.CharField(max_length=30, verbose_name='名称')
    desc = models.TextField(max_length=200, verbose_name='描述')
    order = models.SmallIntegerField()
    skuid = models.ManyToManyField(to=GoodsskuClassModel, verbose_name='和商品sku多对多')
    choic = (
        (False, '未上架'),
        (True, '已上架'),
    )
    shelves = models.BooleanField(choices=choic, verbose_name='是否上架')

    class Meta:
        db_table = 'HomeActarea'
        verbose_name = '首页活动专区'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

www/apps/goods/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views import View

from db.base_view import VerifyLoginView
from goods.models import GoodsSPUModel, GoodsskuClassModel, GoodsClassModel, BannerModel, IndexActModel, HomeActarea


class IndexView(VerifyLoginView):
    def get(self,request):
        #获得轮播商品
        banner=BannerModel.objects.filter(is_delete=False)
        #获得首页活动专区
        act=HomeActarea.objects.filter(is_delete=False)
        #首页活动表
        index=IndexActModel.objects.all()
        context={
            'banner':banner,
            'act':act,
            'index':index
        }
        return render(request,'goods/index.html',context=context)
    def post(self,request):
        pass
class CategoryView(VerifyLoginView):
    def get(self,request):
        # 查询所有的分类
        goods = GoodsClassModel.objects.filter(is_delete=False)
        # 查询所有的商品
        goods_skus = GoodsskuClassModel.objects.filter(is_delete=False)
        context={
            'goods':goods,
            'goods_skus':goods_skus,
        }
        return render(request,'goods/category.html',context=context)
    def post(self,request):
        pass
class DetailView(View):
    def get(self,request,id):
        goods = GoodsskuClassModel.objects.get(pk=id)
        context={
            'goods':goods
            }
        return render(request,'goods/detail.html',context=context)
class TidingsView(VerifyLoginView):
    def get(self,request):
        return render(request,'goods/tidings.html')
    def post(self,request):
        pass
class CityView(VerifyLoginView):
    def get(self,request):
        return render(request,'goods/city.html')
    def post(self,request):
        pass

www/templates/goods/category.html
{% extends 'common/Goods_parents.html' %}
{% load static %}
{% block title %}
<title>超市列表</title>
{% endblock %}
{% block content %}
    <header data-am-widget="header" class="am-header am-header-default sq-head ">
        <div class="am-header-left am-header-nav">
            <a href="javascript:history.back()" class="">
                <i class="am-icon-chevron-left"></i>
            </a>
        </div>
        <div class="cate-search">
            <input type="text" class="cate-input" placeholder="请输入您要的搜索的产品关键词"/>
            <input type="button" class="cate-btn"/>
        </div>
    </header>
    <div style="height: 49px;"></div>
    <ul class="list-nav">
        <li class="current"><a href="">综合</a></li>
        <li><a href="">销量</a></li>
        <li><a href=""><i class="list-price">价格</i></li>
        <li><a href="">新品</a></li>
    </ul>
    <div class="content-list">
        <div class="list-left">
            {% for goods in goods %}
                <li class="current"><a href="">{{ goods.classname }}</a></li>
            {% endfor %}
        </div>
        <div class="list-right">
            <ul class="list-pro">
                {% for goods_skus in goods_skus %}
                    <li>
                        <a href="{% url 'goods:详情' goods_skus.pk %}"><img src="{{ MEDIA_URL }}{{ goods_skus.goodslogo }}" class="list-pic"/></a>
                        <div class="shop-list-mid" style="width: 65%;">
                            <div class="tit"><a href="{% url 'goods:详情' goods_skus.pk %}"> {{ goods_skus.goodsname }}{{ goods_skus.goodsspu_id.SPUname }}</a></div>
                            <div class="am-gallery-desc">￥{{ goods_skus.goodsprice }}</div>
                            <p>销量：{{ goods_skus.stock }}{{ goods_skus.unit.unitname }}</p>
                        </div>
                        <div class="list-cart">
                            <div class="d-stock ">
                                <a class="decrease">-</a>
                                <input id="num" readonly="" class="text_box" name="" type="text" value="0">
                                <a class="increase">+</a>
                            </div>
                        </div>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <!--底部-->
    <div style="height: 55px;"></div>
    <div class="fix-bot">
        <div class="fix-bot-cart"><i>8</i></div>
        <a href="tureorder.html" class="list-js">去结算</a>
        <a href="tureorder.html" class="list-jsk">一键快购</a>
        <!--<div class="js-text">
           <p><b>￥217.80</b></p>
           <p class="js-car">购物满50元免运费</p>
     </div>-->
    </div>

{% endblock %}

www/templates/goods/city.html
{% extends 'common/Goods_parents.html' %}
{% load static%}
{% block title %}
<title>城市</title>
{% endblock %}
{% block content %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">选择城市</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="city-list">
	    	<li class="curr"><a href="">南昌</a></li>
	    	<li><a href="">长沙</a></li>
	    	<li><a href="">北京</a></li>
	    </ul>
{% endblock%}

www/templates/goods/detail.html
{% extends 'common/Goods_parents.html' %}
{% load static %}
{% block title %}
<title>详情</title>
{% endblock %}
{% block head_js %}
		<script>
        	function changeImage(){
              document.getElementById("imgflag").src="images/redherat.png";
           }
        </script>
{% endblock %}

		<style>
			.am-slider-default .am-control-nav{ text-align: center;}
			.am-slider-default .am-control-nav li a.am-active{ background: #cb2527;}
			.am-slider-default .am-control-nav li a{ border: 0; width: 10px; height: 10px;}
		</style>
	<body>
		{% block content %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">商品详情</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <!--图片轮换-->
		<div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
		  <ul class="am-slides">
              {% for Album in goods.goodsalbummodel_set.all %}
              <li><img src="{{ MEDIA_URL }}{{ Album.photourl }}" /></li>
              {% endfor %}
		  </ul>
		</div>
		<div class="detal-info" style="position: relative; width: 100%;">
			<p>{{ goods.goodsname }}{{ goods.goodsspu_id.SPUname }}</p>
			<h2>商城价：<span>￥{{ goods.goodsprice}}</span></h2>
			<div class="heart">
				<img src="{% static 'images/redherat.png' %}" width="25" id="imgflag" onclick="changeImage()" />
				<p>收藏</p>
			</div>
		</div>
		<div class="d-amount">
        	<h4>数量：</h4>
            <div class="d-stock">
              <a class="decrease">-</a>
                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
                <input id="id" type="hidden" value="644">
                <a class="increase">+</a>
               <span id="dprice" class="price" style="display:none"> 36</span>
            </div>
        </div>
        <div style="background: #eee; height: 10px;"></div>
        <div class="am-tabs detail-list" data-am-tabs>
		  <ul class="am-tabs-nav am-nav am-nav-tabs">
		    <li class="am-active"><a href="#tab1">商品详情</a></li>
		    <li><a href="#tab2">商品评论</a></li>
		  </ul>

		  <div class="am-tabs-bd">
		    <div class="am-tab-panel am-fade am-in am-active detail " id="tab1" >
                        {{ goods.goodsspu_id.SPUdetails|safe }}
		    </div>
		    <div class="am-tab-panel am-fade detail " id="tab2">
		         <!--<div class="comment">
		         	<span>好评：</span>
		         	<div class="com-good"></div>
		         	<span>100%</span>
		         </div>
		         <div class="comment">
		         	<span>中评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>
		         <div class="comment">
		         	<span>差评：</span>
		         	<div class="com-bad"></div>
		         	<span>0%</span>
		         </div>-->
		         <ul class="comment-list">
		           <li class="current"><a href="">全部</a></li>
		           <li><a href="">好评（20）</a></li>
		           <li><a href="">中评（5）</a></li>
		           <li><a href="">差评（0）</a></li>
		         </ul>
		         <ul class="comment-pic">
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         	<li>
		         		<div class="tit">
		         			<img src="{% static 'images/tx.png' %}" class="tx" />
		         			<span>songke2014</span>
		         			<i> [2016-01-01]</i>
		         		</div>
		         		<div class="comment-con">
		         			买了些给家人，都说不错！
		         		</div>
		         	</li>
		         </ul>
		    </div>
		  </div>
		</div>


		<!--底部-->
 <div style=" height: 55px;"></div>
 <ul class="fix-shopping">
 	<li><a href="shopcart.html" class="join">加入购物车</a></li>
 	<li><a href="tureorder.html" class="imm-buy">立即购买</a></li>
 </ul>
		{% endblock %}
{% block js %}
<script>
	//购物数量加减
	$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})
</script>
{% endblock %}
    </body>

www/templates/goods/index.html
{% extends 'common/parents.html' %}
{% load static %}
{% block title %}
    <title>超市首页</title>
{% endblock %}

{% block header %}
    <header data-am-widget="header" class="am-header am-header-default sq-head1">
        <div class="am-header-left am-header-nav">
            <a href="city.html" class="" style="color: #fff;">
                <img src="{% static 'images/city.png' %}"/>
                <p style="font-size: 12px; margin-top: -35px;" id="info">全国</p>
            </a>
        </div>
        <h1 class="am-header-title1">
            <div class="search-box">
                <a href="village.html" class="index-search">荣耀10C手机</a>
                <!--  <input type="submit" value="" class="search-icon" /> -->
            </div>
        </h1>
        <div class="am-header-right am-header-nav">
            <a href="tidings.html" class="">
                <div class="messgae"><span>10</span></div>
            </a>
        </div>
    </header>
    <div style="height: 49px;"></div>
{% endblock %}



{% block content %}
    <!--图片轮换-->
    <div class="am-slider am-slider-default" data-am-flexslider id="demo-slider-0">
        <ul class="am-slides">
            {% for banner in banner %}
            <li><img src="{{ MEDIA_URL }}{{ banner.photourl }}"/></li>
            {% endfor %}


        </ul>
    </div>
    <!--导航-->
    <ul class="sq-nav">
        <li>
            <div class="am-gallery-item">
                <a href="recharge.html" class="">
                    <img src="{% static 'images/icon.png' %}"/>
                    <p>充值</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="javascript:;" class="index-qd">
                    <img src="{% static 'images/icon1.png' %}"/>
                    <p>签到</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="yhq.html" class="">
                    <img src="{% static 'images/icon2.png' %}"/>
                    <p>红包</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="" class="">
                    <img src="{% static 'images/icon3.png' %}"/>
                    <p>即将上线</p>
                </a>
            </div>
        </li>
    </ul>
    <ul class="sq-nav1">
        <li>
            <div class="am-gallery-item">
                <a href="speed.html" class="">
                    <img src="{% static 'images/icon4.png' %}"/>
                    <p>零食飞速</p>
                </a>
            </div>
        </li>
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:超市' %}" class="">
                    <img src="{% static 'images/icon5.png' %}"/>
                    <p>超市</p>
                </a>
            </div>
        </li>

    </ul>
    <div class="h-line"></div>
    <!--不规则展示-->
    <div class="index-product">
        {% for act in act %}
          <div class="index-pro-lr"><a href=""><img src="{{ MEDIA_URL }}{{ act.skuid.goodslogo }}"/></a></div>
        {% endfor %}
    </div>

    <!--不规则展示-->
    <div class="h-line"></div>
    <!-- 特色专区-->
    <div class="sq-title">
        <img src="{% static 'images/ts.png' %}" width="26"/>
        特色专区
    </div>
    <ul data-am-widget="gallery" class="am-gallery pro-list am-avg-sm-2 am-avg-md-2 am-avg-lg-4 am-gallery-default">
    {% for index in index %}
        <li>
            <div class="am-gallery-item">
                <a href="{% url 'goods:详情' index.pk %}" class="">
                    <img src="{{ MEDIA_URL }}{{ index.photourl }}"/>
                    <h3 class="am-gallery-title">{{ index.name }}</h3>
                    <div class="am-gallery-desc">￥52</div>
                </a>
            </div>
        </li>
         {% endfor %}
    </ul>
    <!--签到-->
    <div class="qd-box">
        <div class="popup-title">
            <span>签到成功</span>
            <div class="popup-close"><i class="iconfont">&#xe602</i></div>
        </div>
        <div class="dq-text">
            <img src="images/qiandao.png" width="40"/>&nbsp; 您已连续签到3天
        </div>
    </div>
    <!--签到-->
{% endblock %}


{% block footer %}
    <!--底部-->
    <div style="height: 55px;"></div>
    <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
        <ul class="am-navbar-nav am-cf am-avg-sm-5">
            <li>
                <a href="index.html" class="curr">
                    <span class="am-icon-home"></span>
                    <span class="am-navbar-label">首页</span>
                </a>
            </li>
            <li>
                <a href="message.html" class="">
                    <span class="am-icon-comments"></span>
                    <span class="am-navbar-label">动态</span>
                </a>
            </li>
            <li>
                <a href="shopcart.html" class="">
                    <span class="am-icon-shopping-cart"></span>
                    <span class="am-navbar-label">购物车</span>
                </a>
            </li>
            <li>
                <a href="allorder.html" class="">
                    <span class="am-icon-file-text"></span>
                    <span class="am-navbar-label">订单</span>
                </a>
            </li>

            <li>
                <a href="member.html" class="">
                    <span class="am-icon-user"></span>
                    <span class="am-navbar-label">我的</span>
                </a>
            </li>
        </ul>
    </div>
{% endblock %}


{% block footer_js %}
		<script type="text/javascript"
				src="https://webapi.amap.com/maps?v=1.4.12&key=613b505b1095908fb4f3e2fa034fe1d1&plugin=AMap.CitySearch"></script>
		<script type="text/javascript">
			//获取用户所在城市信息
			function showCityInfo() {
				//实例化城市查询类
				var citysearch = new AMap.CitySearch();
				//自动获取用户IP，返回当前城市
				citysearch.getLocalCity(function (status, result) {
					if (status === 'complete' && result.info === 'OK') {
						if (result && result.city && result.bounds) {
							var cityinfo = result.city;
							var citybounds = result.bounds;
							document.getElementById('info').innerHTML = cityinfo;
							//地图显示当前城市
							map.setBounds(citybounds);
						}
					} else {
						document.getElementById('info').innerHTML = result.info;
					}
				});
			}

			showCityInfo();
		</script>
{% endblock %}

www/templates/goods/shopcart.html
{% extends 'common/Goods_parents.html' %}
{% load static %}
{% block title %}
购物车
{% endblock %}

{% block content %}
		<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">购物车</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <!--购物车空的状态-->
	    <div class="login-logo">
	    	<img src="images/care.png">
	    	<p>亲、您的购物车还是空空的哦，快去装满它!</p>
	    	<a href="index.html" class="goshopping">前去逛逛</a>
	    </div>
	    <ul class="shopcart-list">
	    	<li>
	    		<label class="am-checkbox am-warning">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
                <a href="detail.html"><img src="images/test3.png" class="shop-pic" /></a>
                <div class="shop-list-mid">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<b class="shop-list-price">￥169 </b>
                </div>
                <div class="list-cart1">
	                <div class="d-stock">
			                <a class="decrease">-</a>
			                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
			                <a class="increase">+</a>
	                </div>
                </div>

	    	</li>
	    	<li>
	    		<label class="am-checkbox am-warning">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
                <a href="detail.html"><img src="images/test3.png" class="shop-pic" /></a>
                <div class="shop-list-mid">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<b class="shop-list-price">￥169 </b>
                </div>
                <div class="list-cart1">
	                <div class="d-stock">
			                <a class="decrease">-</a>
			                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
			                <a class="increase">+</a>
	                </div>
                </div>

	    	</li>
	    	<li>
	    		<label class="am-checkbox am-warning">
                 <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
                </label>
                <a href="detail.html"><img src="images/test3.png" class="shop-pic" /></a>
                <div class="shop-list-mid">
                	<div class="tit"><a href="detail.html">法国加力果12个装 进口新鲜水果 嘎啦苹果 包邮</a></div>
                	<b class="shop-list-price">￥169 </b>
                </div>
                <div class="list-cart1">
	                <div class="d-stock">
			                <a class="decrease">-</a>
			                <input id="num" readonly="" class="text_box" name="" type="text" value="1">
			                <a class="increase">+</a>
	                </div>
                </div>

	    	</li>
	    	<div style="height: 10px; background: #eee;"></div>
	    </ul>

	    <div class="shop-fix">

	    	<label class="am-checkbox am-warning">
               <input type="checkbox" checked="checked" value="" data-am-ucheck checked>
            </label>
            <a class="del">全选</a>
            <a href="tureorder.html" class="js-btn">去结算</a>
            <div class="js-text">
            	<P>合计：<b>￥217.80</b></P>
            	<p class="js-car">免费配送</p>
            </div>
	    </div>

<!--底部-->
 <div style="height: 55px;"></div>
 <div data-am-widget="navbar" class="am-navbar am-cf am-navbar-default sq-foot am-no-layout" id="">
      <ul class="am-navbar-nav am-cf am-avg-sm-5">
          <li>
            <a href="index.html" class="">
                <span class="am-icon-home"></span>
                <span class="am-navbar-label">首页</span>
            </a>
          </li>
          <li>
            <a href="message.html" class="">
                <span class="am-icon-comments"></span>
                <span class="am-navbar-label">动态</span>
            </a>
          </li>
          <li>
            <a href="shopcart.html" class="">
                <span class="am-icon-shopping-cart"></span>
                <span class="am-navbar-label">购物车</span>
            </a>
          </li>
          <li>
            <a href="allorder.html" class="">
                <span class="am-icon-file-text"></span>
                <span class="am-navbar-label">订单</span>
            </a>
          </li>

          <li>
            <a href="member.html" class="curr">
                <span class="am-icon-user"></span>
                <span class="am-navbar-label">我的</span>
            </a>
          </li>
      </ul>
</div>

{% endblock %}
 
 
{% block js %}
<script>
	//购物数量加减
	$(function(){
		$('.increase').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			current_num += 1;
			self.siblings('input').val(current_num);
			update_item(self.siblings('input').data('item-id'));
		})
		$('.decrease').click(function(){
			var self = $(this);
			var current_num = parseInt(self.siblings('input').val());
			if(current_num > 1){
				current_num -= 1;
				self.siblings('input').val(current_num);
				update_item(self.siblings('input').data('item-id'));
			}
		})
	})
</script>
{% endblock %}

www/templates/goods/tidings.html
{% extends 'common/Goods_parents.html' %}
{% load static%}
{% block content %}
<header data-am-widget="header" class="am-header am-header-default sq-head ">
			<div class="am-header-left am-header-nav">
				<a href="javascript:history.back()" class="">
					<i class="am-icon-chevron-left"></i>
				</a>
			</div>
			<h1 class="am-header-title">
  	            <a href="" class="">消息中心</a>
            </h1>
	    </header>
	    <div style="height: 49px;"></div>
	    <ul class="mess">
	    	<li>
	    		<a href="">
	    		<h2>商城活动，快来参与</h2>
	    		<p class="con">年底感恩活动震撼来袭啦！为回馈和感恩大家，一元抢购活动震撼开场！我们准备了丰富多样的商品，一元就能抢购，赶紧把喜欢的商品带回家吧！</p>
	    	    <div class="time"><span>16-01-06</span><i>查看详情 ></i></div>
	    		</a>
	    	</li>
	    	<li>
	    		<a href="">
	    		<h2>商城活动，快来参与</h2>
	    		<p class="con">年底感恩活动震撼来袭啦！为回馈和感恩大家，一元抢购活动震撼开场！我们准备了丰富多样的商品，一元就能抢购，赶紧把喜欢的商品带回家吧！</p>
	    	    <div class="time"><span>16-01-06</span><i>查看详情 ></i></div>
	    		</a>
	    	</li>
	    </ul>
{% endblock %}